version: '2'
services:
  account-oxapp-vertx-service:
    build: account-oxapp-vertx-service
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=oxapp
      - POSTGRES_PASSWORD=stream
      - POSTGRES_DB=oxappdb
      - "27017:27017"